export const colorLabelMap: Record<string, string> = {
  "#ffffff": "White",
  "#111111": "Black",
  "#585858": "Grey",
  "#ABABAB": "Light Grey",
  "#82A9CC": "Blue Grey",
  "#7DB5EA": "Light Blue",
  "#4599E8": "Blue",
  "#1D7ED7": "Dark Blue",
  "#6D2EFF": "Purple",
  "#8559ED": "Violet",
  "#D50BBA": "Pink",
  "#ED59C8": "Rose",
  "#E71341": "Dark Red",
  "#FF5667": "Red",
  "#118845": "Green",
  "#49976B": "Sage",
};

export const iconLabelMap: Record<string, string> = {
  coffee: "Coffee Icon",
  fork_spoon: "Fork and Spoon Icon",
  book_2: "Book 2 Icon",
  shopping_cart: "Shopping Cart Icon",
  directions_car: "Car Icon",
  stadia_controller: "Controller Icon",
  extension: "Extension Icon",
  flight: "Flight Icon",
  rewarded_ads: "Rewarded Ads Icon",
  sports_bar: "Sports Bar Icon",
  sprint: "Sprint Icon",
  bakery_dining: "Bakery Dining Icon",
  celebration: "Celebration Icon",
  bar_chart_4_bars: "Bar Chart Icon",
  admin_meds: "Admin Meds Icon",
  cognition_2: "Cognition Icon",
  favorite: "Favorite Icon",
};
